### ISSUE TITLE
Lack of proper commits/history

### ISSUE THREAD

**Issue by Manouchehri** [blackberry/android-linux-kernel#1]
Throwing the entire kernel into one commit is less than ideal, it's difficult to see what changes were actually made. At the bare minimum e062944f7b92ae4bb0a5581cc88840df75128ddd should be rebased onto whichever commit BlackBerry forked the Android kernel from.

**Comment by timwindsor** [comment]
Following the requiremetns of the GPL, files changed by BlackBerry contain a copyright notice. The commit history will not be published.

**Comment by Manouchehri** [comment]
Thanks for the tip about the copyright notice, I should be able to split the files apart properly with that.

Could you let me know approximately which commit (and repository) that this kernel was forked from? e.g., 9a1f3257d1f5013ae7dfeb8f2171b777950ab375 @ https://android.googlesource.com/device/ti/panda This isn't a requirement by the GPL, but it would save me a lot of time and I can figure it out manually if I have to.

**Comment by luislobo** [comment]
@Manouchehri look for CONFIG_BBRY in the source code too, those are conditionals added by Blackberry

**Comment by Manouchehri** [comment]
On a related note, here's a great example of another vendor that also crushes their Git history.

https://github.com/allwinner-zh/linux-3.4-sunxi/issues/17#issuecomment-218809068

I'd be willing to bet there's been a couple critical security patches applied very late or completely missed on this kernel tree. Feel free to prove me wrong.
