### ISSUE TITLE
no sources for the apparently included exFAT driver

### ISSUE THREAD

**Issue by thestinger** [blackberry/android-linux-kernel#3]
It appears that an exFAT driver has been included as an extension to the kernel, but the sources are missing. The sources as used by the BlackBerry Priv need to be published to comply with the GPL2.

**Comment by Manouchehri** [comment]
Paging @dlegaultbbry, any update on this?

**Comment by ctravisbbry** [comment]
Hi David and thestinger,

AFAIK the exfat driver is an apk download.  It is not required to be included in the source.

Chris

**Comment by Manouchehri** [comment]
@ctravisbbry Which APK?

**Comment by ctravisbbry** [comment]
It's in the google play store...MicrosoftexFAT for Blackberry.  If you have an exfat formatted sd card in your device, it will detect and show a notification to download it.

**Comment by Manouchehri** [comment]
Thank you!
